spring:
  application:
    name: auth-service

  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/finflow_auth}
    username: ${AUTH_DB_USERNAME:finflow}
    password: ${AUTH_DB_PASSWORD:finflow}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8081}
